"""Windows reminder scheduling via Task Scheduler (schtasks).

Generates a self-deleting notification script under ``~/.dictadesk/reminders``
and registers a one-shot scheduled task that fires at the requested time.

The notification falls back across plyer -> win10toast -> ``msg`` and always
plays a short beep via ``winsound``.
"""

from __future__ import annotations

import json
import re
import subprocess
import sys
from datetime import datetime, timedelta
from pathlib import Path

_DEFAULT_MESSAGE = "Hatirlatici"
_SEPARATORS = ("->", "=>", "|")


def _scripts_dir() -> Path:
    d = Path.home() / ".dictadesk" / "reminders"
    d.mkdir(parents=True, exist_ok=True)
    return d


def _sanitise(text: str, max_len: int = 200) -> str:
    cleaned = (
        text.replace("\\", "")
        .replace('"', "")
        .replace("'", "")
        .replace("\n", " ")
        .replace("\r", "")
        .strip()
    )
    return cleaned[:max_len] or _DEFAULT_MESSAGE


def _parse_when(spec: str, now: datetime) -> datetime:
    s = spec.strip()
    if not s:
        raise ValueError("reminder_bad_format")
    low = s.lower()

    # Relative: +10m / +2h / +1d / +30s / +30 (minutes default)
    rel = re.fullmatch(r"\+\s*(\d+)\s*([smhd]?)", low)
    if rel:
        n = int(rel.group(1))
        unit = rel.group(2) or "m"
        delta = {
            "s": timedelta(seconds=n),
            "m": timedelta(minutes=n),
            "h": timedelta(hours=n),
            "d": timedelta(days=n),
        }[unit]
        return now + delta

    # Turkish relative: "5 dakika sonra", "2 saat sonra", "30 saniye sonra"
    tr = re.search(r"(\d+)\s*(saniye|sn|dakika|dk|saat|gun|g\u00fcn)\b", low)
    if tr and "sonra" in low:
        n = int(tr.group(1))
        unit = tr.group(2)
        if unit in ("saniye", "sn"):
            delta = timedelta(seconds=n)
        elif unit in ("dakika", "dk"):
            delta = timedelta(minutes=n)
        elif unit == "saat":
            delta = timedelta(hours=n)
        else:
            delta = timedelta(days=n)
        return now + delta

    # Absolute: YYYY-MM-DD HH:MM
    abs_m = re.search(r"(\d{4})-(\d{2})-(\d{2})\s+(\d{1,2}):(\d{2})", s)
    if abs_m:
        return datetime(
            int(abs_m.group(1)),
            int(abs_m.group(2)),
            int(abs_m.group(3)),
            int(abs_m.group(4)),
            int(abs_m.group(5)),
        )

    # Date only: YYYY-MM-DD -> 09:00
    date_m = re.fullmatch(r"(\d{4})-(\d{2})-(\d{2})", s)
    if date_m:
        return datetime(
            int(date_m.group(1)),
            int(date_m.group(2)),
            int(date_m.group(3)),
            9,
            0,
        )

    time_m = re.search(r"(\d{1,2}):(\d{2})", low)

    # Turkish "yarin [HH:MM]" / "bugun [HH:MM]"
    if "yarin" in low or "yar\u0131n" in low:
        base = now + timedelta(days=1)
        h, mi = (int(time_m.group(1)), int(time_m.group(2))) if time_m else (9, 0)
        return base.replace(hour=h, minute=mi, second=0, microsecond=0)
    if "bugun" in low or "bug\u00fcn" in low:
        h, mi = (int(time_m.group(1)), int(time_m.group(2))) if time_m else (9, 0)
        return now.replace(hour=h, minute=mi, second=0, microsecond=0)

    # Bare HH:MM -> today, or tomorrow if already passed
    if time_m:
        h, mi = int(time_m.group(1)), int(time_m.group(2))
        target = now.replace(hour=h, minute=mi, second=0, microsecond=0)
        if target <= now:
            target += timedelta(days=1)
        return target

    raise ValueError("reminder_bad_format")


def parse_reminder(payload: str, now: datetime | None = None) -> tuple[datetime, str]:
    """Parse a reminder payload into (target_datetime, message).

    Raises ValueError with a reason code on malformed input.
    """
    now = now or datetime.now()
    text = (payload or "").strip()
    if not text:
        raise ValueError("missing")
    when_part = text
    message = _DEFAULT_MESSAGE
    for sep in _SEPARATORS:
        if sep in text:
            when_part, message = text.split(sep, 1)
            when_part = when_part.strip()
            message = message.strip() or _DEFAULT_MESSAGE
            break
    target = _parse_when(when_part, now)
    return target, message


def _write_notify_script(task_name: str, message: str) -> Path:
    script_path = _scripts_dir() / f"{task_name}.py"
    msg_literal = json.dumps(message)
    script_body = f"""# Auto-generated by DictaDesk reminder -- do not edit
import pathlib
message = {msg_literal}
notified = False
try:
    from plyer import notification
    notification.notify(title="DictaDesk Hatirlatici", message=message, timeout=15)
    notified = True
except Exception:
    pass
if not notified:
    try:
        from win10toast import ToastNotifier
        ToastNotifier().show_toast("DictaDesk Hatirlatici", message, duration=15, threaded=False)
        notified = True
    except Exception:
        pass
if not notified:
    try:
        import subprocess
        subprocess.run(["msg", "*", "/TIME:30", message], check=False)
    except Exception:
        pass
try:
    import time
    import winsound
    for freq in (800, 1000, 1200):
        winsound.Beep(freq, 180)
        time.sleep(0.08)
except Exception:
    pass
try:
    pathlib.Path(__file__).unlink(missing_ok=True)
except Exception:
    pass
"""
    script_path.write_text(script_body, encoding="utf-8")
    return script_path


def _schedule_windows(target_dt: datetime, task_name: str, script_path: Path) -> bool:
    python_exe = Path(sys.executable)
    pythonw = python_exe.parent / "pythonw.exe"
    if pythonw.exists():
        python_exe = pythonw

    xml_path = _scripts_dir() / f"{task_name}.xml"
    xml_content = (
        '<?xml version="1.0" encoding="UTF-16"?>\n'
        '<Task version="1.2" xmlns="http://schemas.microsoft.com/windows/2004/02/mit/task">\n'
        "  <RegistrationInfo><Description>DictaDesk Reminder</Description></RegistrationInfo>\n"
        "  <Triggers><TimeTrigger>\n"
        f'    <StartBoundary>{target_dt.strftime("%Y-%m-%dT%H:%M:%S")}</StartBoundary>\n'
        "    <Enabled>true</Enabled>\n"
        "  </TimeTrigger></Triggers>\n"
        "  <Actions><Exec>\n"
        f"    <Command>{python_exe}</Command>\n"
        f'    <Arguments>"{script_path}"</Arguments>\n'
        "  </Exec></Actions>\n"
        "  <Settings>\n"
        "    <MultipleInstancesPolicy>IgnoreNew</MultipleInstancesPolicy>\n"
        "    <DisallowStartIfOnBatteries>false</DisallowStartIfOnBatteries>\n"
        "    <StopIfGoingOnBatteries>false</StopIfGoingOnBatteries>\n"
        "    <StartWhenAvailable>true</StartWhenAvailable>\n"
        "    <ExecutionTimeLimit>PT5M</ExecutionTimeLimit>\n"
        "    <Enabled>true</Enabled>\n"
        "  </Settings>\n"
        "  <Principals><Principal>\n"
        "    <LogonType>InteractiveToken</LogonType>\n"
        "    <RunLevel>LeastPrivilege</RunLevel>\n"
        "  </Principal></Principals>\n"
        "</Task>"
    )
    xml_path.write_text(xml_content, encoding="utf-16")
    try:
        result = subprocess.run(
            ["schtasks", "/Create", "/TN", task_name, "/XML", str(xml_path), "/F"],
            capture_output=True,
            text=True,
        )
    finally:
        try:
            xml_path.unlink(missing_ok=True)
        except Exception:
            pass
    if result.returncode != 0:
        try:
            script_path.unlink(missing_ok=True)
        except Exception:
            pass
        return False
    return True


def schedule_reminder(payload: str, now: datetime | None = None) -> tuple[bool, str]:
    """Schedule a reminder. Returns (ok, info) where info is a friendly time or a reason code."""
    if sys.platform != "win32":
        return False, "reminder_not_windows"
    now = now or datetime.now()
    try:
        target_dt, message = parse_reminder(payload, now=now)
    except ValueError as exc:
        return False, str(exc) or "reminder_bad_format"

    if target_dt <= now:
        return False, "reminder_past"

    safe_msg = _sanitise(message)
    task_name = f"DictaDeskReminder_{target_dt.strftime('%Y%m%d_%H%M%S')}"
    try:
        script_path = _write_notify_script(task_name, safe_msg)
    except Exception:
        return False, "reminder_schedule_failed"

    try:
        ok = _schedule_windows(target_dt, task_name, script_path)
    except Exception:
        try:
            script_path.unlink(missing_ok=True)
        except Exception:
            pass
        return False, "reminder_schedule_failed"

    if not ok:
        return False, "reminder_schedule_failed"

    return True, target_dt.strftime("%Y-%m-%d %H:%M")
